BASE_DIR=`pwd`
LIB_DIR="${BASE_DIR}/../lib"
ANTLR_RELEASE="4.7.1"
ANTLR_DIR="${LIB_DIR}/antlr-${ANTLR_RELEASE}.jar"
PY4J_DIR="${LIB_DIR}/py4j-0.10.9.jar"
BIN_DIR="${BASE_DIR}/../bin"
export CLASSPATH=".:${ANTLR_DIR}:${PY4J_DIR}:${BIN_DIR}:$CLASSPATH"
